### ISSUE TITLE
Target Variable interchanged 

### ISSUE THREAD

**Issue by kamalkraj** [HackerEarth/indiahacks-ml-2017#1]
In RF_Starter.ipynb i think that while encoding target variable some of them interchanged ,
Pls check Cell no. 6 and 8

If i am wrong,sorry

**Comment by saraswatmks** [comment]
Hi @kamalkraj the variables encoded are DetectedCamera and Target. Both are encoded differently. The target variable is encoded based on the column sequence specified in the submission file. 
Please close the issue if your doubt is clear now.
