### ISSUE TITLE
int is not iterable

### ISSUE THREAD

**Issue by rishabhkumarjha** [HackerEarth/indiahacks-ml-2017#2]
TypeError                                 Traceback (most recent call last)
<ipython-input-1-e167a010103d> in <module>()
     11 train = pd.DataFrame.from_dict(data_dict_1, orient='index')
     12 train
---> 13 train.reset_index(level=0, inplace=True)
     14 train.rename(columns = {'index':'ID'},inplace=True)
     15 train.shape

c:\python27\lib\site-packages\pandas\core\frame.pyc in reset_index(self, level, drop, inplace, col_level, col_fill)
   3053                 # to ndarray and maybe infer different dtype
   3054                 level_values = _maybe_casted_values(lev, lab)
-> 3055                 if level is None or i in level:
   3056                     new_obj.insert(0, name, level_values)
   3057 

TypeError: argument of type 'int' is not iterable

**Comment by saraswatmks** [comment]
Hi @rishabhkumarjha I tried running the code and got no error. In case, you are still unable to overcome this error, you can try using method given here: https://github.com/HackerEarth/indiahacks-ml-2017/blob/master/Hotstar_RF_Script.ipynb

**Comment by vishwali** [comment]
Getting the same error. Is it Python2.7 or 3.5?

**Comment by rishabhkumarjha** [comment]
yes I see it works in python 3.6 but not in python2.7
