### ISSUE TITLE
Why the Detected Camera encoding and Target encoding is different?

### ISSUE THREAD

**Issue by chowdhurySudip** [HackerEarth/indiahacks-ml-2017#3]
if you use a different encoding for Detected Camera and Target, the following result will come.
Before encoding --
![screenshot_2017-06-14_19-25-37](https://user-images.githubusercontent.com/18592572/27136013-c0c01f48-5137-11e7-85c8-e711e1ce6eac.png)
After Encoding --
![screenshot_2017-06-14_19-26-01](https://user-images.githubusercontent.com/18592572/27136036-d721b6c0-5137-11e7-89e9-09fbc547b0bd.png)

So, if there is a trick behind this please let me know.

**Comment by saraswatmks** [comment]
Hi @buildithub if you check carefully (more rows), Detected Camera variable is not same as the target variable. Check the data description. That's why they have been encoded differently.
